language: node_js
sudo: required
node_js:
- node
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: 2MtH6OJHecjufh5KxnPxshU2cnTgub9Wx7ZHHSnFlrWZtrBWRf6pIkLh7eevOoOfWAerhuIw4ms4aGSoTNI2dFOdCQC9Djgq3xVT3Sp1xeyE34KFSwPjiVmZPPAtBLl5uwbCoeENt7PAfjZvzl8gnFXMoSUVp3KLgJ5rYZ6BtxVde3/T/I5BcmOvvElf9tPanFSYrlI24DgLzmN0SgT45eajPYhh67Rp2gCPtoqqqOT1dJBaz8O6WwArLl6ACm9ysoki1esxzx4zOTM1641GSQQ4OsgqrNwNi6Gjh0zlAygx0YCYeI39QUBZGEhmN8ScNacv1hEDLUCYT0ts+Ng3d267CTU9ADeMDO5Ggtuj+40bIkAFNRXyBZ7MgXplUDpr49NQWH7wH2Am3DAIVu+lPH63PL5IaghtIrnRbzlrtBAsr+hFDRw8h/xoi7AaiuSWv/dSQJ7unx+IudYfvb0d0j4DU/RctkvrqhqJn66dpov72ks4QAIRrram+MKaFPSGJr5U8USkHqOC8ku1xBON/PQCjymfrDonBG4A4IesLVUPixgSpY9jHshWYhRQ1cP4t/ma66dsJCV+xCj1Au2Ex4jBtKJFE2oHlSq5vx5X/7WenO2KI0iEGPbw/W3LkJXOY6rVZ/hpt7X+xjI42y66z05Jdzqjz1I1e3wOIKFaBwE=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - dbus
    - gcc-4.8
    - g++-4.8
    - libglib2.0-dev
before_script:
- npm install -g node-gyp
- npm install -g grunt-cli npm
